server:
  port:8080

logging:
  level:
    root: INFO

spring:
  profiles:
    default: test

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: jibber-jabber
  resource: login-app
  public-client: true

